services:
  web-staging:
    image: cicd-web-demo:staging
    container_name: cicd_web_staging
    ports:
      - "8081:80"

  web-production:
    image: cicd-web-demo:production
    container_name: cicd_web_production
    ports:
      - "8082:80"
